name: generate-gradle-wrapper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Commit Wrapper
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git commit -m "Add Gradle wrapper" || echo "No changes"
          git push
