name: Java Build with Gradle

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: '実行するクラス名（完全修飾名）'
        required: true
      method_name:
        description: '実行するメソッド名'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Set up Java
         uses: actions/setup-java@v4
         with:
            java-version: '21'
            distribution: 'temurin'

       - name: Grant execute permission for gradlew
         run: chmod +x gradlew

       - name: Build with Gradle
         run: ./gradlew build

       - name: Run jar
         run: |
           java -jar build/libs/*.jar \
             "${{ github.event.inputs.class_name }}" \
             "${{ github.event.inputs.method_name }}"
