name: Java Run

on:
  workflow_dispatch:
    inputs:
      arg1:
        description: "クラス名"
        required: true
      arg2:
        description: "メソッド名"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Java Build
          name: app-jar

      - name: Run
        run: |
          java -jar testFromSapporo.jar "${{ github.event.inputs.arg1 }}" "${{ github.event.inputs.arg2 }}"
